from typing import Protocol

from contexts.chatbots.domain.chatbot import Chatbot
from contexts.chatbots.domain.value_objects import ChatbotId
from shared.application.tenant_context import TenantId


class ChatbotRepository(Protocol):
    def add(self, bot: Chatbot) -> Chatbot: ...
    def get(self, tenant_id: TenantId, chatbot_id: ChatbotId) -> Chatbot | None: ...
    def list(self, tenant_id: TenantId) -> list[Chatbot]: ...
    def exists_name(self, tenant_id: TenantId, name: str) -> bool: ...
    def update(self, bot: Chatbot) -> None: ...
    def delete(self, tenant_id: TenantId, chatbot_id: ChatbotId) -> None: ...
